apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocr-images-pvc-ranged-7-10
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: shared

---

apiVersion: batch/v1
kind: Job
metadata:
  name: ocr-image-gen-ranged-7-10
spec:
  parallelism: 20
  template:
    metadata:
      labels:
        app: ocr-images
    spec:
      restartPolicy: Never
      containers:
        - name: lpr
          image: registry.datexis.com/tsteffek/licenseplatereconstructor:2fa3af3a6c4efa8dcccdbc710c3d3718f71ac4e6
          command: [ "python" ]
          args: [ "bin/GenerateImages.py",
                  "--save_dir", "/var/lib/images",
                  "--num_train", "25000",
                  "--num_test", "2500",
                  "--num_val", "2500",
                  "--width", "1387",f
                  "--height", "445",
                  "--max_chars", "10",
                  "--min_chars", "7",
                  "--margin_xy", "10",
                  "--min_char_width", "100",
                  "--max_char_width", "140"
          ]
          resources:
            requests:
              cpu: 0.1
              memory: 5Gi
            limits:
              memory: 10Gi
          volumeMounts:
            - name: ocr-images
              mountPath: /var/lib/images
      volumes:
        - name: ocr-images
          persistentVolumeClaim:
            claimName: ocr-images-pvc-ranged-7-10
      imagePullSecrets:
        - name: private-registry-auth
      nodeSelector:
        cpu: epyc-7542