apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lpr-images-pvc-template-blank-lam5
spec:
  dataSource:
    name: lpr-images-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: lpr-train-template-blank-lam5
spec:
  template:
    metadata:
      labels:
        app: lpr
    spec:
      restartPolicy: Never
      containers:
        - name: lpr
          image: registry.datexis.com/tsteffek/licenseplatereconstructor:e1f05dacd78c2487bca4520bd3c1ca1962ad277a
          command: [ "python" ]
          args: [ "bin/TrainLPR.py",
                  "--ocr_path", "/var/lib/models/OCR/ranged-7-10/lightning_logs/version_9/checkpoints/epoch=6-step=3422.ckpt",
                  "--path", "/var/lib/images",
                  "--early_stopping",
                  "--max_epochs", "20",
                  "--min_epochs", "5",
                  "--default_root_dir", "/var/lib/models/lpr/blank",
                  "--batch_size", "480",
                  "--lr", "0.0001",
                  "--gpus", "-1",
                  "--precision", "16",
                  "--progress_bar_refresh_ratio", "0.1",
                  "--limit_val_batches", "0.1",
                  "--use_template",
                  "--lam", "5",
            #                  "--template_path", "templates/template.jpg"
                  "--template_path", "templates/template_blank.jpg"
            #                  "--auto_lr_find" # 0.002754228703338169
            #                  "--overfit_batches", "10",
            #                  "--accelerator", "ddp"
          ]
          resources:
            requests:
              nvidia.com/gpu: 1
              memory: 60Gi
            limits:
              nvidia.com/gpu: 1
              memory: 100Gi
          volumeMounts:
            - name: lpr-images
              mountPath: /var/lib/images
            - name: ocr-models
              mountPath: /var/lib/models
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: ocr-models
          persistentVolumeClaim:
            claimName: ocr-models-pvc
        - name: lpr-images
          persistentVolumeClaim:
            claimName: lpr-images-pvc-template-blank-lam5
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      nodeSelector:
        gpu: a100
