apiVersion: batch/v1
kind: Job
metadata:
  name: ocr-test
spec:
  template:
    metadata:
      labels:
        app: ocr
    spec:
      restartPolicy: Never
      containers:
        - name: lpr
          image: registry.datexis.com/tsteffek/licenseplatereconstructor:e7df031dbd78c9e62725e3228139599dcfa6a045
          command: [ "python" ]
          args: [ "bin/TrainOCR.py",
                  "--path", "/var/lib/images",
                  "--no_train",
                  "--batch_size", "40",
                  "--gpus", "-1",
                  '--resume_from_checkpoint', "/var/lib/models/default/lightning_logs/version_13/checkpoints/epoch=7-step=190893.ckpt"
          ]
          resources:
            requests:
              nvidia.com/gpu: 1
              memory: 100Gi
            limits:
              nvidia.com/gpu: 1
              memory: 150Gi
          volumeMounts:
            - name: ocr-images
              mountPath: /var/lib/images
            - name: ocr-models
              mountPath: /var/lib/models
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: ocr-images
          persistentVolumeClaim:
            claimName: ocr-images-pvc-train
        - name: ocr-models
          persistentVolumeClaim:
            claimName: ocr-models-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      nodeSelector:
        gpu: a100