apiVersion: batch/v1
kind: Job
metadata:
  name: ocr-train-ranged-7-10
spec:
  template:
    metadata:
      labels:
        app: ocr
    spec:
      restartPolicy: Never
      containers:
        - name: lpr
          image: registry.datexis.com/tsteffek/licenseplatereconstructor:190929b3ca7acead4872f1e63f786e122e4c1518
          command: [ "python" ]
          args: [ "bin/TrainOCR.py",
                  "--path", "/var/lib/images",
                  "--width_mult", "0.5",
                  "--early_stopping",
                  "--max_epochs", "200",
                  "--default_root_dir", "/var/lib/models/range-7-10",
                  "--batch_size", "256",
                  "--gpus", "-1",
                  "--precision", "16",
                  "--target_size", "0.2",
                  "--progress_bar_refresh_ratio", "0.1",
          ]
          resources:
            requests:
              nvidia.com/gpu: 1
              memory: 80Gi
            limits:
              nvidia.com/gpu: 1
              memory: 160Gi
          volumeMounts:
            - name: ocr-images
              mountPath: /var/lib/images
            - name: ocr-models
              mountPath: /var/lib/models
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: ocr-models
          persistentVolumeClaim:
            claimName: ocr-models-pvc
        - name: ocr-images
          persistentVolumeClaim:
            claimName: ocr-images-pvc-ranged-7-10
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      nodeSelector:
        gpu: a100