apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocr-images-pvc-ranged-7-10-lr-cos
spec:
  dataSource:
    name: ocr-images-pvc-ranged-7-10-small
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: ocr-train-ranged-7-10-lr-cos
spec:
  template:
    metadata:
      labels:
        app: ocr
    spec:
      restartPolicy: Never
      containers:
        - name: ocr
          image: registry.datexis.com/tsteffek/licenseplatereconstructor:8a004923ae7c6362879f17b9d2bc389c75c489bd
          command: [ "python" ]
          args: [ "bin/TrainOCR.py",
                  "--path", "/var/lib/images",
            #                  "--no_train",
                  "--width_mult", "0.5",
                  "--early_stopping",
                  "--max_epochs", "150",
                  "--min_epochs", "20",
                  "--default_root_dir", "/var/lib/models/OCR/ranged-7-10",
                  "--batch_size", "512",
                  "--lr", "0.002754228703338169",
                  "--lr_schedule", "cosine",
                  "--lr_warm_up", "linear",
                  "--gpus", "-1",
                  "--precision", "16",
                  "--progress_bar_refresh_ratio", "0.1",
                  "--auto_lr_find", "True" # for 1024: 0.002754228703338169
            #                  "--accelerator", "ddp"
          ]
          resources:
            requests:
              nvidia.com/gpu: 1
              memory: 100Gi
            limits:
              nvidia.com/gpu: 1
              memory: 200Gi
          volumeMounts:
            - name: ocr-images
              mountPath: /var/lib/images
            - name: ocr-models
              mountPath: /var/lib/models
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: ocr-models
          persistentVolumeClaim:
            claimName: ocr-models-pvc
        - name: ocr-images
          persistentVolumeClaim:
            claimName: ocr-images-pvc-ranged-7-10-lr-cos
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      nodeSelector:
        gpu: a100
